wip: Start attempt2
--ssh-dest works but if not supplied a todo! error:

 $ cargo run "Starting\|version:\|ERROR" --since=-1d
   Compiling srch-srvr-logs v0.1.0 (/home/wink/prgs/rust/myrepos/srch-srvr-logs)
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `/home/wink/prgs/rust/myrepos/srch-srvr-logs/target/debug/srch-srvr-logs 'Starting\|version:\|ERROR' --since=-1d`
 Process eth1.service:
 thread 'main' panicked at 'not yet implemented: Local execution isn't supported yet :)', src/main.rs:53:13